### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode

### ISSUE THREAD

**Issue by parnz** [stooged/bin2html-900#1]
On Windows with python3 you'll get error: `UnicodeDecodeError: 'charmap' codec can't decode 0x... in position xxx: character maps to <undefined>`

fix this error by add `encoding="utf-8"` to` open()` function in bin2html.py

Line 23:  From
`with open (templatefile, "r") as f:`
To
`with open (templatefile, "r",encoding="utf-8") as f:`

Line 28: From
`f = open(filename.replace('.bin','.html'), 'w+') `
To
`f = open(filename.replace('.bin','.html'), 'w+',encoding="utf-8") `

[Here is the link to stackoverflow](https://stackoverflow.com/a/42495690/1933934)

**Comment by stooged** [comment]
updated code to reflect those changes, thankyou for pointing that out.
