### ISSUE TITLE
Can't get to run on OSX

### ISSUE THREAD

**Issue by Doyle4** [stooged/bin2html-900#2]
Im getting this error message if you could help?

Last login: Wed Jan  5 02:00:31 on ttys000
Macbook-Pro:~ doyle$ python3 /Users/doyle/Desktop/bin2html.py /Users/doyle/Desktop/LinuxLoader-900.bin
Traceback (most recent call last):
  File "/Users/doyle/Desktop/bin2html.py", line 23, in <module>
    with open (templatefile, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'template.dat'
Macbook-Pro:~ doyle$ 

I have also tried:
python3 bin2html.py LinuxLoader-900.bin
python3 /Users/doyle/Desktop/bin2html.py LinuxLoader-900.bin
python3 /Users/doyle/Desktop/bin2html.py /Users/doyle/Desktop/LinuxLoader-900.bin
python3 bin2html.py /Users/doyle/Desktop/LinuxLoader-900.bin

Not sure what im doing wrong.
Thanks.

**Comment by stooged** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'template.dat'

something is preventing the script finding the template.dat file

make sure you have 
/Users/doyle/Desktop/bin2html.py
and
/Users/doyle/Desktop/template.dat

**Comment by Doyle4** [comment]
Solved, Thank you!

Really sorry about these questions, still learning this but getting better each time.
Worked and now have a html file, thank you.
